version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceTimePlanningPlugin"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/ServiceTimePlanningPlugin.Integration.Test"
  schedule:
    interval: daily
